import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile, mkdir } from "node:fs/promises";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { installHostSurface } from "../src/mcp/host-install.mjs";
import { nativePath } from "./helpers.mjs";
const execFileAsync=promisify(execFile);
const common={nodePath:"/opt/node",cliPath:"/opt/threadspan/src/cli.mjs",bridgeConfigPath:"/home/me/.threadspan/config.jsonc",connectorTokenFile:"/home/me/.threadspan/connector-token",statusLinePath:"/opt/threadspan/integrations/claude-code-threadspan/statusline.mjs"};
test("host installer preserves unrelated Cursor and Grok MCP configuration with rollback",async(t)=>{const home=await mkdtemp(join(tmpdir(),"threadspan-host-install-"));t.after(()=>rm(home,{recursive:true,force:true}));await mkdir(join(home,".cursor"),{recursive:true});await writeFile(join(home,".cursor","mcp.json"),'{"mcpServers":{"kept":{"command":"other"}}}\n');const cursor=await installHostSurface("cursor",{home,...common});assert.ok(cursor.backupPath);assert.match(await readFile(cursor.hostConfigPath,"utf8"),/"kept"/);await mkdir(join(home,".grok"),{recursive:true});await writeFile(join(home,".grok","config.toml"),'[ui]\nscreen_mode="minimal"\n');const grok=await installHostSurface("grok",{home,...common});const text=await readFile(grok.hostConfigPath,"utf8");assert.match(text,/screen_mode/);assert.match(text,/mcp_servers\.threadspan/);assert.doesNotMatch(text,/Bearer |secret-value/)});
test("Hermes remains staged and explicit",async(t)=>{const home=await mkdtemp(join(tmpdir(),"threadspan-hermes-stage-"));t.after(()=>rm(home,{recursive:true,force:true}));await assert.rejects(installHostSurface("hermes",{home,...common}),/allow-preview/);const result=await installHostSurface("hermes",{home,...common,allowPreview:true});assert.equal(result.stagedOnly,true);assert.match(await readFile(result.hostConfigPath,"utf8"),/include:/)});
test("Claude Code reverse host remains Preview-gated and stages MCP plus statusLine",async(t)=>{const home=await mkdtemp(join(tmpdir(),"threadspan-claude-host-"));t.after(()=>rm(home,{recursive:true,force:true}));await assert.rejects(installHostSurface("claude-code",{home,...common}),/allow-preview/);const result=await installHostSurface("claude-code",{home,...common,allowPreview:true,pluginSource:"/opt/threadspan/integrations/claude-code-threadspan"});assert.equal(result.stagedOnly,true);assert.equal(result.liveTested,false);assert.equal(result.nativePickerPreserved,true);assert.match(await readFile(result.hostConfigPath,"utf8"),/"type": "stdio"/);assert.match(await readFile(result.settings.hostConfigPath,"utf8"),/"statusLine"/);assert.match(result.pluginSource,/claude-code-threadspan/)});

test("production CLI host install emits a connector-only /mcp shim",async(t)=>{const root=await mkdtemp(join(tmpdir(),"threadspan-cli-host-install-"));t.after(()=>rm(root,{recursive:true,force:true}));const configPath=join(root,"config.json"),target=join(root,"mcp.json"),connectorTokenFile=join(root,"connector-token"),ownerTokenFile=join(root,"owner-token");await writeFile(configPath,JSON.stringify({server:{host:"127.0.0.1",port:9753,authTokenFile:ownerTokenFile},defaults:{provider:"mock",mode:"consult",model:"mock-model"},providers:{mock:{adapter:"mock",model:"mock-model",capabilities:["consult","integrated","delegate"]}}}));await writeFile(connectorTokenFile,"connector-secret\n",{mode:0o600});const cli=nativePath(new URL("../src/cli.mjs",import.meta.url));await execFileAsync(process.execPath,[cli,"host","install","--config",configPath,"--host","cursor","--token-file",connectorTokenFile,"--target",target]);const installed=await readFile(target,"utf8"),shim=JSON.parse(installed).mcpServers.threadspan;assert.equal(shim.args[shim.args.indexOf("--token-file")+1],connectorTokenFile);assert.equal(shim.args[shim.args.indexOf("--remote")+1],"http://127.0.0.1:9753/mcp");assert.equal(shim.args.includes(ownerTokenFile),false);assert.doesNotMatch(installed,/connector-secret/)});
