import assert from "node:assert/strict";
import { resolve } from "node:path";
import test from "node:test";
import { createHostSurfaceInstallPacket, createMcpShimDefinition, renderClaudeCodeMcpConfig, renderClaudeCodeSettings, renderCursorMcpConfig, renderGrokMcpToml, renderHermesMcpYaml } from "../src/mcp/host-config.mjs";
import { listHostSurfaces, nativeRecoveryContract } from "../src/core/host-surfaces.mjs";

const options={nodePath:"/opt/node",cliPath:"/opt/threadspan/src/cli.mjs",bridgeConfigPath:"/home/me/.threadspan/config.jsonc",connectorTokenFile:"/home/me/.threadspan/connector-token",statusLinePath:"/opt/threadspan/integrations/claude-code-threadspan/statusline.mjs"};
test("host surfaces have explicit tiers and native recovery",()=>{assert.deepEqual(listHostSurfaces().map(x=>[x.id,x.tier]),[["codex","primary"],["grok","enhanced"],["cursor","standard"],["claude-code","preview"],["hermes","preview"]]);assert.equal(nativeRecoveryContract("grok").fallback,"grok-resume");assert.equal(nativeRecoveryContract("cursor").fallback,"agent-resume");assert.equal(nativeRecoveryContract("claude-code").fallback,"claude --resume");assert.equal(nativeRecoveryContract("claude-code").crossHostTranscriptCopy,false);const hermesRecovery=nativeRecoveryContract("hermes");assert.equal(hermesRecovery.transport,"hermes-acp-session");assert.equal(hermesRecovery.available,false);assert.equal(hermesRecovery.availability,"blocked-until-source-bound-tool-isolation");assert.equal(hermesRecovery.liveTested,false);assert.equal(hermesRecovery.crossProcessResume,false);assert.equal(hermesRecovery.crossHostTranscriptCopy,false);assert.equal(hermesRecovery.codexFallback,false);const hermes=listHostSurfaces().find(x=>x.id==="hermes");assert.equal(hermes.forward,false);assert.match(hermes.forwardReason,/non-narrowable built-in agent toolset.*native MCP servers/);assert.equal(hermes.status,"preview");assert.equal(hermes.liveTested,false);assert.equal(hermes.nativePickerPreserved,true)});
test("MCP host configs use the connector token file and scoped /mcp endpoint",()=>{const shim=createMcpShimDefinition(options);assert.equal(shim.command,resolve(options.nodePath));assert.equal(shim.args[0],resolve(options.cliPath));assert.deepEqual(shim.args.slice(-2),["--token-file",resolve(options.connectorTokenFile)]);assert.equal(shim.args[shim.args.indexOf("--remote")+1],"http://127.0.0.1:8743/mcp");const cursor=renderCursorMcpConfig({mcpServers:{kept:{command:"other"}}},options),grok=renderGrokMcpToml(options),hermes=renderHermesMcpYaml(options);assert.match(cursor,/"kept"/);assert.match(cursor,/"threadspan"/);assert.match(grok,/\[mcp_servers\.threadspan\]/);for(const tool of ["bridge_status","bridge_models","bridge_accounts","consult","integrated"])assert.match(hermes,new RegExp(`- ${tool}`));assert.doesNotMatch(hermes,/\n\s*- delegate\b/);assert.match(hermes,/read-only/);assert.doesNotMatch(cursor+grok+hermes,/auth-token|Bearer |api[_-]?key|secret-value/i);assert.equal(createHostSurfaceInstallPacket("grok",options).storesCredentialValues,false);const packet=createHostSurfaceInstallPacket("hermes",options);assert.equal(packet.status,"preview");assert.equal(packet.liveTested,false);assert.equal(packet.nativePickerPreserved,true);assert.equal(packet.recovery,"unavailable")});
test("MCP host configs reject direct reuse of the owner main-token file",()=>{assert.throws(()=>createMcpShimDefinition({...options,ownerTokenFile:options.connectorTokenFile}),/must differ from the owner main-token file/)});
test("Claude Code reverse config preserves native state and stages statusLine without replacing the picker",()=>{const mcp=renderClaudeCodeMcpConfig({mcpServers:{kept:{command:"other"}},futureField:{kept:true}},options);const settings=renderClaudeCodeSettings({theme:"dark"},options);assert.match(mcp,/"type": "stdio"/);assert.match(mcp,/"futureField"/);assert.match(mcp,/"kept"/);assert.match(settings,/"statusLine"/);assert.match(settings,/statusline\.mjs/);assert.match(settings,/"theme": "dark"/);assert.doesNotMatch(mcp+settings,/Bearer |api[_-]?key|secret-value/i);const packet=createHostSurfaceInstallPacket("claude-code",options);assert.equal(packet.status,"preview");assert.equal(packet.liveTested,false);assert.equal(packet.nativePickerReplaceable,false)});
