import { existsSync } from "node:fs";
import { chmod, copyFile, mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, resolve } from "node:path";

const START_MARKER = "# >>> threadspan managed block >>>";
const END_MARKER = "# <<< threadspan managed block <<<";
const LEGACY_MARKERS = [
  ["# >>> cursor-codex-bridge managed block >>>", "# <<< cursor-codex-bridge managed block <<<"],
];

/**
 * Resolve the default Codex configuration path.
 * @param {NodeJS.ProcessEnv} [environment] Environment.
 * @returns {string}
 */
export function resolveCodexConfigPath(environment = process.env) {
  const codexHome = environment.CODEX_HOME ? resolve(environment.CODEX_HOME) : resolve(homedir(), ".codex");
  return resolve(codexHome, "config.toml");
}

/**
 * Render a self-contained Codex TOML block for the Responses provider and Consult MCP skill.
 *
 * @param {{
 *   bridgeUrl?: string,
 *   mcpRemoteUrl?: string,
 *   tokenEnv?: string,
 *   providerId?: string,
 *   cliPath: string,
 *   bridgeConfigPath: string,
 *   defaultProvider?: string,
 *   defaultModel?: string,
 *   integratedProvider?: string,
 *   integratedModel?: string,
 *   delegateProvider?: string,
 *   delegateModel?: string,
 *   mcpServerId?: string,
 *   modelCatalogPath?: string,
 * }} options Render options.
 * @returns {string}
 */
export function renderCodexConfigBlock(options) {
  const bridgeUrl = options.bridgeUrl ?? "http://127.0.0.1:8743/v1";
  const mcpRemoteUrl = options.mcpRemoteUrl;
  const tokenEnv = options.tokenEnv ?? "THREADSPAN_TOKEN";
  const providerId = options.providerId ?? "threadspan_bridge";
  const defaultProvider = options.defaultProvider ?? "cursor-ultra";
  const defaultModel = options.defaultModel ?? "auto";
  const integratedProvider = options.integratedProvider ?? "nous";
  const integratedModel = options.integratedModel ?? "deepseek/deepseek-v4-flash-0731";
  const delegateProvider = options.delegateProvider ?? defaultProvider;
  const delegateModel = options.delegateModel ?? defaultModel;
  const mcpServerId = options.mcpServerId ?? "consult";
  const cliPath = resolve(options.cliPath);
  const bridgeConfigPath = resolve(options.bridgeConfigPath);

  const modelCatalogLine = options.modelCatalogPath ? `model_catalog_json = ${tomlString(resolve(options.modelCatalogPath))}\n\n` : "";

  return `${START_MARKER}
# Generated by Threadspan. Re-run "threadspan codex install" to update.
# The local daemon must be running for model-provider profiles.${mcpRemoteUrl ? " MCP tools proxy to the same daemon so provider pools and admission limits are shared." : " MCP tools use an embedded bridge process."}

${modelCatalogLine}[model_providers.${tomlBareKey(providerId)}]
name = "Threadspan"
base_url = ${tomlString(bridgeUrl)}
env_key = ${tomlString(tokenEnv)}
wire_api = "responses"
request_max_retries = 2
stream_max_retries = 3
stream_idle_timeout_ms = 1800000

[profiles.threadspan_consult]
model_provider = ${tomlString(providerId)}
model = ${tomlString(`consult/${defaultProvider}/${defaultModel}`)}

[profiles.threadspan_integrated]
model_provider = ${tomlString(providerId)}
model = ${tomlString(`integrated/${integratedProvider}/${integratedModel}`)}

[profiles.threadspan_delegate]
model_provider = ${tomlString(providerId)}
model = ${tomlString(`delegate/${delegateProvider}/${delegateModel}`)}

[mcp_servers.${tomlBareKey(mcpServerId)}]
command = ${tomlString(process.execPath)}
args = [${[tomlString(cliPath), '"mcp"', '"--config"', tomlString(bridgeConfigPath), ...(mcpRemoteUrl ? ['"--remote"', tomlString(mcpRemoteUrl)] : [])].join(", ")}]
startup_timeout_sec = 30
tool_timeout_sec = 7200
${END_MARKER}`;
}

/**
 * Install or replace the managed bridge block in a Codex config file with an atomic write and backup.
 * @param {string} configPath Codex config path.
 * @param {string} block Managed TOML block.
 * @param {{backup?: boolean}} [options] Install options.
 * @returns {Promise<{path: string, backupPath?: string, replaced: boolean}>}
 */
export async function installCodexConfigBlock(configPath, block, options = {}) {
  const path = resolve(configPath);
  await mkdir(dirname(path), { recursive: true });
  const existing = existsSync(path) ? await readFile(path, "utf8") : "";
  const { text, replaced } = replaceManagedBlock(existing, block);
  let backupPath;
  if (existing && options.backup !== false) {
    backupPath = `${path}.backup-${new Date().toISOString().replace(/[:.]/g, "-")}`;
    await copyFile(path, backupPath);
  }
  await atomicWrite(path, text.endsWith("\n") ? text : `${text}\n`);
  await chmod(path, 0o600).catch(() => undefined);
  return { path, ...(backupPath ? { backupPath } : {}), replaced };
}

/**
 * Remove the managed bridge block from a Codex config file without touching unrelated TOML.
 * @param {string} configPath Codex config path.
 * @returns {Promise<{path: string, removed: boolean}>}
 */
export async function uninstallCodexConfigBlock(configPath) {
  const path = resolve(configPath);
  if (!existsSync(path)) return { path, removed: false };
  const existing = await readFile(path, "utf8");
  const range = findManagedBlock(existing);
  if (!range) return { path, removed: false };
  const next = `${existing.slice(0, range.start).trimEnd()}\n${existing.slice(range.end).trimStart()}`.trim();
  await atomicWrite(path, next ? `${next}\n` : "");
  return { path, removed: true };
}

/**
 * Replace an existing managed block or append a new block.
 * @param {string} existing Existing TOML.
 * @param {string} block New managed block.
 * @returns {{text: string, replaced: boolean}}
 */
export function replaceManagedBlock(existing, block) {
  const range = findManagedBlock(existing);
  if (!range) {
    const prefix = existing.trimEnd();
    return { text: `${prefix}${prefix ? "\n\n" : ""}${block.trim()}\n`, replaced: false };
  }
  return {
    text: `${existing.slice(0, range.start)}${block.trim()}${existing.slice(range.end)}`,
    replaced: true,
  };
}

/**
 * Locate the managed marker range, including one trailing newline when present.
 * @param {string} text TOML text.
 * @returns {{start: number, end: number}|undefined}
 */
function findManagedBlock(text) {
  for (const [startMarker, endMarker] of [[START_MARKER, END_MARKER], ...LEGACY_MARKERS]) {
    const start = text.indexOf(startMarker);
    if (start < 0) continue;
    const markerEnd = text.indexOf(endMarker, start);
    if (markerEnd < 0) throw new Error(`Found '${startMarker}' without matching end marker`);
    let end = markerEnd + endMarker.length;
    if (text[end] === "\r" && text[end + 1] === "\n") end += 2;
    else if (text[end] === "\n") end += 1;
    return { start, end };
  }
  return undefined;
}

/**
 * Atomically replace a text file in its directory.
 * @param {string} path Target path.
 * @param {string} text Text.
 * @returns {Promise<void>}
 */
async function atomicWrite(path, text) {
  const temporary = `${path}.tmp-${process.pid}-${Date.now()}`;
  await writeFile(temporary, text, { mode: 0o600 });
  await rename(temporary, path);
}

/**
 * Encode a TOML basic string.
 * @param {string} value Value.
 * @returns {string}
 */
export function tomlString(value) {
  return JSON.stringify(String(value));
}

/**
 * Render a safe TOML bare key or a quoted key when punctuation requires it.
 * @param {string} value Key.
 * @returns {string}
 */
function tomlBareKey(value) {
  return /^[A-Za-z0-9_-]+$/.test(value) ? value : tomlString(value);
}

export { START_MARKER, END_MARKER };
